/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tft_garits.GUI;

import java.util.ArrayList;
import java.util.Collections;
import tft_garits.Account.User;

/**
 *
 * @author George Kemp
 */
public class EditUserForm extends Form {
    /**
     * Creates new form AddUserForm
     */
    public EditUserForm(GUI gui) {
        super(gui);
        initComponents();
        
        refreshUserIdBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fullNameField = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        JobRoleBox = new javax.swing.JComboBox<>();
        UserIdBox = new javax.swing.JComboBox<>();
        deleteButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Settings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Edit Existing User");

        jLabel2.setText("User ID:");

        jLabel3.setText("Password:");

        jLabel4.setText("Full Name:");

        jLabel5.setText("Job Role:");

        fullNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameFieldActionPerformed(evt);
            }
        });

        editButton.setText("Save Changes");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        JobRoleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Foreperson", "Franchisee", "Mechanic", "Receptionist" }));

        UserIdBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIdBoxActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete User");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Hourly Rate, £:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fullNameField)
                                    .addComponent(jPasswordField1)
                                    .addComponent(JobRoleBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UserIdBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rateField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UserIdBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JobRoleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(editButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // back to settings
        this.dispose();
        gui.run("MAINMENU");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // take in field details & edit user's info in database
        Object selected = UserIdBox.getSelectedItem();
        int selectedIndex = UserIdBox.getSelectedIndex();
        
        if (selected != null){
            String user_name = selected.toString();
            String password = new String(jPasswordField1.getPassword());
            String full_name = fullNameField.getText();
            String account_type = JobRoleBox.getSelectedItem().toString();
            
            if (!password.equals("") && !password.equals("password")){
                gui.databaseHandler.executeStatement("UPDATE login SET password=? WHERE user_name=?", password, user_name);
            }
            
            gui.databaseHandler.executeStatement("UPDATE staff SET staff_name=? WHERE user_name=?", full_name, user_name);
            gui.databaseHandler.executeStatement("UPDATE login SET account_type=? WHERE user_name=?", account_type, user_name);
            
            try {
                float rate = Float.parseFloat(rateField.getText());
                gui.databaseHandler.executeStatement("UPDATE staff SET hourly_rate = " + rate + " WHERE user_name = '" + user_name + "'");
            } catch (NumberFormatException e){
                
            }
            refreshUserIdBox();
            UserIdBox.setSelectedIndex(selectedIndex);
            editButton.setText("Saved");
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        //remove user from database
        Object selected = UserIdBox.getSelectedItem();
        editButton.setText("Save Changes");
        
        if (selected != null){
            deleteUser(selected.toString());
            refreshUserIdBox();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void UserIdBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIdBoxActionPerformed
        //on selecting userID, populate fields
        Object selected = UserIdBox.getSelectedItem();
        editButton.setText("Save Changes");
        
        if (selected != null){
            String user_name = selected.toString();
            String full_name = gui.databaseHandler.executeStringQuery("SELECT staff_name FROM staff WHERE user_name=?", user_name, "staff_name");
            String account_type = gui.databaseHandler.executeStringQuery("SELECT account_type FROM login WHERE user_name=?", user_name, "account_type");
            System.out.println(user_name + ", " + full_name + ", " + account_type);

            fullNameField.setText(full_name);
            jPasswordField1.setText("password");
            //Foreperson, Franchisee, Mechanic, Receptionist
            int index = account_type.equals("Foreperson") ? 1 : 
                        account_type.equals("Franchisee") ? 2 : 
                        account_type.equals("Mechanic") ? 3 :  
                        account_type.equals("Receptionist") ? 4 : 0;
            JobRoleBox.setSelectedIndex(index);
            
            float rate = gui.databaseHandler.executeFloatQuery("SELECT hourly_rate FROM staff WHERE user_name = ?", user_name, "hourly_rate");
            if (rate != -1){
                rateField.setText(String.format("%.2f", rate));
            }
        } else {
            //UserIdBox.setSelectedIndex(0);
            jPasswordField1.setText("");
            fullNameField.setText("");
            JobRoleBox.setSelectedIndex(0);
        }
    }//GEN-LAST:event_UserIdBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JobRoleBox;
    private javax.swing.JComboBox<String> UserIdBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField fullNameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField rateField;
    // End of variables declaration//GEN-END:variables

    private void refreshUserIdBox() {
        UserIdBox.removeAllItems();
        
        ArrayList<String> usernames = gui.databaseHandler.getUsernames();
        
        Collections.sort(usernames);
        
        UserIdBox.addItem(null);
        usernames.forEach((u) -> {
            UserIdBox.addItem(u);
        });
    }
    
    private void deleteUser(String deleteName){
        gui.databaseHandler.executeStatement("DELETE FROM staff WHERE user_name='" + deleteName + "'");
        gui.databaseHandler.executeStatement("DELETE FROM login WHERE user_name='" + deleteName + "'");
    }
}
