/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tft_garits.GUI;

import java.util.ArrayList;
import java.util.Collections;
import tft_garits.Account.User;
import tft_garits.Database.ValueObject;

/**
 *
 * @author George Kemp
 */
public class EditPartForm extends Form {
    /**
     * Creates new form AddUserForm
     */
    public EditPartForm(GUI gui) {
        super(gui);
        initComponents();
        
        refreshPartNameBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        partNameBox = new javax.swing.JComboBox<>();
        deleteButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        thresholdField = new javax.swing.JTextField();
        descriptionField = new javax.swing.JTextField();
        stockAmountField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Stock");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Edit Part");

        jLabel2.setText("Part Name");

        jLabel3.setText("Description:");

        jLabel4.setText("Price:");

        jLabel5.setText("Stock Amount:");

        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });

        editButton.setText("Save Changes");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        partNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partNameBoxActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete Part");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Threshold:");

        descriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(156, 156, 156))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jButton1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priceField)
                            .addComponent(partNameBox, 0, 258, Short.MAX_VALUE)
                            .addComponent(thresholdField)
                            .addComponent(descriptionField)
                            .addComponent(stockAmountField))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(partNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(stockAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(thresholdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // back to settings
        this.dispose();
        gui.run("STOCK");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // take in field details & edit user's info in database
        Object selected = partNameBox.getSelectedItem();
        int selectedIndex = partNameBox.getSelectedIndex();
        
        if (selected != null){
            String part_name = selected.toString();
            String description = descriptionField.getText();
            try {
                float price = Float.parseFloat(priceField.getText());
                try {
                    
                    int amount = Integer.parseInt(stockAmountField.getText());
                    int threshold = Integer.parseInt(thresholdField.getText());

                    String sql =  "UPDATE part"
                                + "SET description =?,"
                                + "SET price =?,"
                                + "SET stock_amount =?,"
                                + "SET threshold =?,"
                                + "WHERE part_name=?;";

                    ArrayList<ValueObject> values = new ArrayList<>();

                    values.add(new ValueObject("String", description));
                    values.add(new ValueObject("float", price));
                    values.add(new ValueObject("int", amount));
                    values.add(new ValueObject("int", threshold));

                    values.add(new ValueObject("String", part_name));

                    gui.databaseHandler.executeArrayInsert(sql, values);

                    refreshPartNameBox();
                    partNameBox.setSelectedIndex(selectedIndex);
                    editButton.setText("Saved");
                } catch (NumberFormatException e){
                    gui.throwErrorForm("Amount & Threshold must be positive whole numbers.");
                }
            } catch (NumberFormatException e){
                gui.throwErrorForm("Price must be a number.");
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        //remove user from database
        Object selected = partNameBox.getSelectedItem();
        editButton.setText("Save Changes");
        
        if (selected != null){
            gui.databaseHandler.executeStatement("DELETE FROM part WHERE part_name='" + selected.toString() + "'");
            refreshPartNameBox();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void partNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partNameBoxActionPerformed
        //on selecting userID, populate fields
        Object selected = partNameBox.getSelectedItem();
        editButton.setText("Save Changes");
        
        if (selected != null){
            String part_name = selected.toString();
            String description = gui.databaseHandler.executeStringQuery("SELECT description FROM part WHERE part_name=?", part_name, "description");
            float price = gui.databaseHandler.executeFloatQuery("SELECT price FROM part WHERE part_name=?", part_name, "price");
            int amount = gui.databaseHandler.executeIntQuery("SELECT stock_amount FROM part WHERE part_name=?", part_name, "stock_amount");
            int threshold = gui.databaseHandler.executeIntQuery("SELECT threshold FROM part WHERE part_name=?", part_name, "threshold");
            
            descriptionField.setText(description);
            priceField.setText(price + "");
            stockAmountField.setText(amount + "");
            thresholdField.setText(threshold  + "");
            
        } else {
            //UserIdBox.setSelectedIndex(0);
            descriptionField.setText("");
            priceField.setText("");
            stockAmountField.setText("0");
            thresholdField.setText("");
        }
    }//GEN-LAST:event_partNameBoxActionPerformed

    private void descriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JButton editButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> partNameBox;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField stockAmountField;
    private javax.swing.JTextField thresholdField;
    // End of variables declaration//GEN-END:variables

    private void refreshPartNameBox() {
        partNameBox.removeAllItems();
        
        ArrayList<String> parts = gui.databaseHandler.getNameArray("SELECT part_name FROM part", "part_name");
        
        Collections.sort(parts);
        
        partNameBox.addItem(null);
        parts.forEach((u) -> {
            partNameBox.addItem(u);
        });
    }
}
