/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tft_garits.GUI;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import tft_garits.Database.ValueObject;

/**
 *
 * @author George Kemp
 */
public class JobsForm extends Form {
    
    private int currentJob;
    /**
     * Creates new form CustomerForm
     */
    public JobsForm(GUI gui) {
        super(gui);
        initComponents();
        currentJob = -1;
        //jobNoTextField.setText(currentJob);
        
        refreshMechanicBox();
        refreshCustomerBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jobNoTextField = new javax.swing.JTextField();
        bookingDateTextField = new javax.swing.JTextField();
        telNoTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        makeTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        jobStatusComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mechanicComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        bayAllocationTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        timeTakenTextField = new javax.swing.JTextField();
        costTextField = new javax.swing.JTextField();
        costVATTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        vehicleRegTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        customerNameBox = new javax.swing.JComboBox<>();
        clearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequiredList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        partsRequiredList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Job Sheet");

        jLabel2.setText("Job no:");

        jLabel3.setText("Vehicle Reg:");

        jLabel4.setText("Customer Name:");

        jLabel5.setText("Booking Date:");

        jLabel6.setText("Tel no:");

        jobNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobNoTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Work Required:");

        createButton.setText("Add New Job");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Make:");

        makeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Model:");

        jobStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Not Started", "In Progress", "Complete", "Cancelled" }));

        jLabel12.setText("Job Status:");

        jLabel13.setText("Mechanic:");

        mechanicComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Bay Allocation:");

        jLabel15.setText("Parts Required:");

        costTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                costTextFieldFocusLost(evt);
            }
        });
        costTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costTextFieldActionPerformed(evt);
            }
        });

        costVATTextField.setEditable(false);

        jLabel16.setText("Time Taken:");

        jLabel17.setText("Cost:");

        jLabel18.setText("Cost + VAT:");

        removeButton.setText("Remove");
        removeButton.setEnabled(false);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        vehicleRegTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleRegTextFieldActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        customerNameBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        clearButton.setText("Clear Fields");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(workRequiredList);

        jScrollPane2.setViewportView(partsRequiredList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(bayAllocationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                            .addComponent(jobStatusComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bookingDateTextField)
                                            .addComponent(telNoTextField)
                                            .addComponent(mechanicComboBox, 0, 154, Short.MAX_VALUE)
                                            .addComponent(customerNameBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(createButton)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(vehicleRegTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(makeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(49, 49, 49)
                                        .addComponent(jobNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchButton)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18))
                                    .addGap(25, 25, 25)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(costVATTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(costTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(timeTakenTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(clearButton))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jobNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchButton))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(vehicleRegTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(makeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(customerNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(bookingDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(telNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jobStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(mechanicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bayAllocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel15)
                                .addGap(110, 110, 110)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(timeTakenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(costVATTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(saveButton)
                    .addComponent(removeButton))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        gui.run("MAINMENU");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jobNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobNoTextFieldActionPerformed

    private void makeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeTextFieldActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // add new, empty job to database
        int job_no = gui.databaseHandler.getNextVal("job", "job_no");
        currentJob = job_no;
        jobNoTextField.setText("" + job_no);
        
        //grey out create & search & jobNoTextField
        jobNoTextField.setEditable(false);
        createButton.setEnabled(false);
        searchButton.setEnabled(false);
        //enable remove & save
        removeButton.setEnabled(true);
        saveButton.setEnabled(true);
        saveButton.setText("Save");
        
        LocalDateTime now = LocalDateTime.now();
        bookingDateTextField.setText(now.format(DateTimeFormatter.ISO_LOCAL_DATE));
    }//GEN-LAST:event_createButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // remove job from database
        int jobID = Integer.parseInt(jobNoTextField.getText());
        gui.databaseHandler.executeStatement("DELETE FROM job WHERE job_no='" + jobID + "'");
        clearAll();
        
        gui.throwErrorForm("Removed job " + jobID);
        
        //enable search, add
        jobNoTextField.setEditable(true);
        createButton.setEnabled(true);
        searchButton.setEnabled(true);
        //disable remove & edit
        removeButton.setEnabled(false);
        saveButton.setEnabled(false);
        saveButton.setText("Save");
    }//GEN-LAST:event_removeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // save changes to database
        if (checkValid()) {
            int jobID = Integer.parseInt(jobNoTextField.getText());
            
            int customerID = gui.databaseHandler.executeIntQuery("SELECT customer_no FROM customer WHERE customer_name=?", 
                                                               customerNameBox.getSelectedItem().toString(), 
                                                              "customer_no");
            
            Integer staffID;
            if (mechanicComboBox.getSelectedItem() == null){
                staffID = null;
            } else {
                staffID = gui.databaseHandler.executeIntQuery("SELECT staff_no FROM staff WHERE staff_name=?", 
                                                               mechanicComboBox.getSelectedItem().toString(), 
                                                              "staff_no");
            }
            
            String reg_no = vehicleRegTextField.getText();
            
            
            
            ArrayList<ValueObject> values = new ArrayList<>();
            //insert vehicle
            //gui.databaseHandler.executeStatement("DELETE FROM vehicle WHERE reg_no='" + reg_no + "'");
            String sql = "INSERT INTO vehicle "
                       + "(reg_no, customer_no, make, model) "
                       + "values (?, ?, ?, ?) "
                       + "ON CONFLICT (reg_no) DO "
                       + "UPDATE SET make = ?, model = ?;";
            
            values.add(new ValueObject("String", reg_no)); //add reg_no
            values.add(new ValueObject("int", customerID)); //add customer_no
            values.add(new ValueObject("String", makeTextField.getText())); //add make
            values.add(new ValueObject("String", modelTextField.getText())); //add model
            values.add(new ValueObject("String", makeTextField.getText())); //add make again
            values.add(new ValueObject("String", modelTextField.getText())); //add model again
            
            gui.databaseHandler.executeArrayInsert(sql, values);
            
            
            //insert job
            sql = "INSERT INTO job "
                    + "(job_no, customer_no, status, date_booked, reg_no, staff_no, totalamount, estimated_time, completion_date)"
                    + "values (?, ?, ?, ?, ?, ?, ?, ?, ?)"
                    + "ON CONFLICT (job_no) DO "
                    + "UPDATE SET status = ?, date_booked = ?, reg_no = ?, staff_no = ?, totalamount = ?, estimated_time = ?, completion_date = ?;";
            
            values.clear();
            
            values.add(new ValueObject("int", jobID)); //add job_no
            values.add(new ValueObject("int", customerID)); //add customer_no
            values.add(new ValueObject("String", jobStatusComboBox.getSelectedItem().toString())); //add status
            values.add(new ValueObject("date", bookingDateTextField.getText())); //add date_booked
            values.add(new ValueObject("String", reg_no)); //add reg_no
            values.add(new ValueObject("int", staffID)); //add staff_no
            values.add(new ValueObject("float", costTextField.getText())); //add totalamount
            values.add(new ValueObject("float", -1f)); //add estimated_time
            values.add(new ValueObject("date", bookingDateTextField.getText())); //add completion_date
            
            values.add(new ValueObject("String", jobStatusComboBox.getSelectedItem().toString())); //add status
            values.add(new ValueObject("date", bookingDateTextField.getText())); //add date_booked
            values.add(new ValueObject("String", reg_no)); //add reg_no
            values.add(new ValueObject("int", staffID)); //add staff_no
            values.add(new ValueObject("float", costTextField.getText())); //add totalamount
            values.add(new ValueObject("float", -1f)); //add estimated_time
            values.add(new ValueObject("date", bookingDateTextField.getText())); //add completion_date
            
            gui.databaseHandler.executeArrayInsert(sql, values);
            
            saveButton.setText("Changes Saved");
            
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void vehicleRegTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleRegTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleRegTextFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        
        int job_no = -1;
        try {
            job_no = Integer.parseInt(jobNoTextField.getText());
            
            if (job_no != -1){
                if (gui.databaseHandler.checkQuery("SELECT job_no FROM job WHERE job_no=?", new ValueObject("int", job_no), "job_no")) {
                    
                    ValueObject job_no_VO = new ValueObject("int", job_no);
                    
                    String reg_no = gui.databaseHandler.executeStringQuery("SELECT reg_no FROM job WHERE job_no=?", job_no_VO, "reg_no");
                    vehicleRegTextField.setText(reg_no);
                    
                    ValueObject reg = new ValueObject("String", reg_no);
                    
                    String make = gui.databaseHandler.executeStringQuery("SELECT make FROM vehicle WHERE reg_no=?", reg, "make");
                    makeTextField.setText(make);
                    
                    String model = gui.databaseHandler.executeStringQuery("SELECT model FROM vehicle WHERE reg_no=?", reg, "model");
                    modelTextField.setText(model);
                    
                    int customer_no = gui.databaseHandler.executeIntQuery("SELECT customer_no FROM vehicle WHERE reg_no=?", reg, "customer_no");
                    ValueObject customer_no_VO = new ValueObject("int", customer_no);
                    
                    String customer_name = gui.databaseHandler.executeStringQuery("SELECT customer_name FROM customer WHERE customer_no=?", customer_no_VO, "customer_name");
                    customerNameBox.setSelectedItem(customer_name);
                    
                    String bookingDate = gui.databaseHandler.executeDateQuery("SELECT date_booked FROM job WHERE job_no=?", job_no_VO, "date_booked");
                    bookingDateTextField.setText(bookingDate);
                    
                    int tel_no = gui.databaseHandler.executeIntQuery("SELECT tel FROM customer WHERE customer_no=?", customer_no_VO, "tel");
                    telNoTextField.setText(tel_no + "");
                    
                    String job_status = gui.databaseHandler.executeStringQuery("SELECT status FROM job WHERE job_no=?", job_no_VO, "status");
                    jobStatusComboBox.setSelectedItem(job_status);
                    
                    int staff_no = gui.databaseHandler.executeIntQuery("SELECT staff_no FROM job WHERE job_no=?", job_no_VO, "staff_no");
                    String mechanic_name = gui.databaseHandler.executeStringQuery("SELECT staff_name FROM staff WHERE staff_no=?", new ValueObject("int", staff_no), "staff_name");
                    mechanicComboBox.setSelectedItem(mechanic_name);
                    
                    bayAllocationTextField.setText("not implemented");
                    
                    float cost = gui.databaseHandler.executeFloatQuery("SELECT totalamount FROM job WHERE job_no=?", job_no_VO, "totalamount");
                    costTextField.setText(cost + "");
                    
                    float timeTaken = gui.databaseHandler.executeFloatQuery("SELECT estimated_time FROM job WHERE job_no=?", job_no_VO, "estimated_time");
                    timeTakenTextField.setText(timeTaken + "");
                    
                    String[] tasks = gui.databaseHandler.getStringArray("SELECT task_desc FROM task WHERE job_no= " + job_no, "task_desc");
                    workRequiredList.setListData(tasks);
                    
                    String[] parts = gui.databaseHandler.getPartsForJob(job_no);
                    
                    partsRequiredList.setListData(parts);
                    
                    //reset button
                    jobNoTextField.setEditable(false);
                    createButton.setEnabled(false);
                    removeButton.setEnabled(true);
                    vatDisplay();
                } else {
                    gui.throwErrorForm("Job no not found in database.");
                }
            }
        } catch (NumberFormatException e){
            gui.throwErrorForm("Job no must be a number.");
        }
        
        //enable remove
    }//GEN-LAST:event_searchButtonActionPerformed

    private void costTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costTextFieldActionPerformed
        // TODO add your handling code here:
        vatDisplay();
    }//GEN-LAST:event_costTextFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearAll();
        
        //enable search, add
        jobNoTextField.setEditable(true);
        createButton.setEnabled(true);
        searchButton.setEnabled(true);
        //disable remove & edit
        removeButton.setEnabled(false);
        saveButton.setEnabled(false);
        saveButton.setText("Save");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void costTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_costTextFieldFocusLost
        vatDisplay();
    }//GEN-LAST:event_costTextFieldFocusLost

    private void clearAll() {
        bayAllocationTextField.setText("");
        bookingDateTextField.setText("");
        costTextField.setText("");
        costVATTextField.setText("");
        customerNameBox.setSelectedIndex(0);
        jobNoTextField.setText("");
        makeTextField.setText("");
        modelTextField.setText("");
        telNoTextField.setText("");
        timeTakenTextField.setText("");
        vehicleRegTextField.setText("");
        
        workRequiredList.setListData(new String[0]);
        partsRequiredList.setListData(new String[0]);
        
        customerNameBox.setSelectedIndex(0);
        jobStatusComboBox.setSelectedIndex(0);
        mechanicComboBox.setSelectedIndex(0);
    }
    
    private boolean someFieldsEmpty(){
        if (jobNoTextField.getText().isEmpty()) return true;
        if (customerNameBox.getSelectedIndex() == 0) return true;
        if (jobStatusComboBox.getSelectedIndex() == 0) return true;
        if (mechanicComboBox.getSelectedIndex() == 0) return true;
        //if (bayAllocationTextField.getText().isEmpty()) return true;
        if (bookingDateTextField.getText().isEmpty()) return true;
        if (vehicleRegTextField.getText().isEmpty()) return true;
        //if (bayAllocationTextField.getText().isEmpty()) return true;
        if (bayAllocationTextField.getText().isEmpty()) return true;
        if (costTextField.getText().isEmpty()) return true;
        if (timeTakenTextField.getText().isEmpty()) return true;
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayAllocationTextField;
    private javax.swing.JTextField bookingDateTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField costTextField;
    private javax.swing.JTextField costVATTextField;
    private javax.swing.JButton createButton;
    private javax.swing.JComboBox<String> customerNameBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jobNoTextField;
    private javax.swing.JComboBox<String> jobStatusComboBox;
    private javax.swing.JTextField makeTextField;
    private javax.swing.JComboBox<String> mechanicComboBox;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JList<String> partsRequiredList;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField telNoTextField;
    private javax.swing.JTextField timeTakenTextField;
    private javax.swing.JTextField vehicleRegTextField;
    private javax.swing.JList<String> workRequiredList;
    // End of variables declaration//GEN-END:variables

    private void refreshMechanicBox() {
        mechanicComboBox.removeAllItems();
        
        ArrayList<String> mechanics = gui.databaseHandler.getMechanics();
        
        Collections.sort(mechanics);
        
        mechanicComboBox.addItem(null);
        mechanics.forEach((u) -> {
            mechanicComboBox.addItem(u);
        });
    }

    private void refreshCustomerBox() {
        customerNameBox.removeAllItems();
        
        ArrayList<String> customers = gui.databaseHandler.getCustomers();
        
        Collections.sort(customers);
        
        customerNameBox.addItem(null);
        customers.forEach((u) -> {
            customerNameBox.addItem(u);
        });
    }
    
    private void vatDisplay(){
        try {
            double vat = Double.parseDouble(costTextField.getText());
            vat = vat*1.17;
            costVATTextField.setText("" +  String.format("%.2f", vat));
        } catch (NumberFormatException e){
            costVATTextField.setText("n/a");
        }
    }

    private boolean checkValid() {
        String reg_no = vehicleRegTextField.getText();
        String customer_name = "";
        if (customerNameBox.getSelectedItem() != null){
            customer_name = customerNameBox.getSelectedItem().toString();
        } 
        
        if (someFieldsEmpty()){
            gui.throwErrorForm("Not all fields complete.");
            return false;
        } else if (!gui.databaseHandler.checkReg(reg_no, customer_name)){
            gui.throwErrorForm("Vehicle " + reg_no + " belongs to another customer.");
            return false;
        }
        return true;
    }
}
