/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tft_garits.GUI;

import tft_garits.Account.Foreperson;
import tft_garits.Account.Franchisee;
import tft_garits.Account.Mechanic;
import tft_garits.Account.Receptionist;

/**
 *
 * @author George Kemp
 */
public class MechanicMenu extends Form {

    /**
     * Creates new form MainMenuForm
     */
    public MechanicMenu(GUI gui) {
        super(gui);
        
        if (gui.currentUser instanceof Franchisee){
            initComponents();
        } else if (gui.currentUser instanceof Foreperson){
            initComponents();
        } else if (gui.currentUser instanceof Mechanic){
            initComponents();
        } else if (gui.currentUser instanceof Receptionist){
            initComponents();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("GARITS");

        jButton3.setText("Tasks");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Job Sheet");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("Log out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // CUSTOMERS
        this.dispose();
        gui.run("CUSTOMERS");
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // STOCK
        this.dispose();
        gui.run("STOCK");
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TASKS
        this.dispose();
        gui.run("TASKS");
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // job sheet
        this.dispose();
        gui.run("JOBSHEET");
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // documents
        this.dispose();
        gui.run("DOCUMENTS");
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        // settings
        this.dispose();
        gui.run("JOBLIST");
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        // LOG OUT
        this.dispose();
        gui.run("LOGIN");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
