/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tft_garits.GUI;

import tft_garits.Account.Foreperson;
import tft_garits.Account.Franchisee;
import tft_garits.Account.Mechanic;
import tft_garits.Account.Receptionist;

/**
 *
 * @author George Kemp
 */
public class ReceptionistMenu extends Form {

    /**
     * Creates new form MainMenuForm
     */
    public ReceptionistMenu(GUI gui) {
        super(gui);
        
        if (gui.currentUser instanceof Franchisee){
            initComponents();
        } else if (gui.currentUser instanceof Foreperson){
            initComponents();
        } else if (gui.currentUser instanceof Mechanic){
            initComponents();
        } else if (gui.currentUser instanceof Receptionist){
            initComponents();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("GARITS");

        jButton2.setText("Stock");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Job Sheet");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Job List");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Log out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton2)
                        .addGap(42, 42, 42)
                        .addComponent(jButton4)
                        .addGap(35, 35, 35)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton7)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addGap(32, 32, 32)
                .addComponent(jButton7)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // CUSTOMERS
        this.dispose();
        gui.run("CUSTOMERS");
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // STOCK
        this.dispose();
        gui.run("STOCK");
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TASKS
        this.dispose();
        gui.run("TASKS");
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // job sheet
        this.dispose();
        gui.run("JOBSHEET");
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // documents
        this.dispose();
        gui.run("DOCUMENTS");
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        // settings
        this.dispose();
        gui.run("JOBLIST");
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        // LOG OUT
        this.dispose();
        gui.run("LOGIN");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
