/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tft_garits.GUI;

import java.util.ArrayList;
import java.util.List;
import tft_garits.Database.ValueObject;

/**
 *
 * @author George Kemp
 */
public class SetPartsForm extends Form {
    
    int task_no;
    
    String[] part_descs;
    Integer[] part_nos;
    
    String[] selected_part_names;
    Integer[] selected_part_nos;
    /**
     * Creates new form SetPartsForm
     */
    public SetPartsForm(GUI gui, String task, int task_no) {
        super(gui);
        initComponents();
        
        this.task_no = task_no;
        
        taskField.setText(task);
        taskField.setEditable(false);
        updatePartsList();
        updateSelectedList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        taskField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        partsList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedList = new javax.swing.JList<>();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Set Parts");

        jLabel2.setText("Task:");

        partsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(partsList);

        selectedList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(selectedList);

        addButton.setText(">");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("<");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Save and Close");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Selected Parts:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToggleButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taskField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 102, Short.MAX_VALUE)
                                .addComponent(jLabel3)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(taskField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        //List<String> selections = partsList.getSelectedValuesList();
        int[] indexes = selectedList.getSelectedIndices();
        if (indexes.length != 0){
            for (int i = 0; i < indexes.length; i++){
                int part_no = selected_part_nos[indexes[i]];
                System.out.println(part_no + ": " + indexes[i] + ", " + i);
                gui.databaseHandler.executeStatement("UPDATE task_part SET amount=amount-1 WHERE ( task_no = " + task_no + " AND part_no = " + part_no + ")");
            }
        }
        
        gui.databaseHandler.executeStatement("DELETE FROM task_part WHERE (amount < 1);");
        updateSelectedList();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        List<String> selections = partsList.getSelectedValuesList();
        if (!selections.isEmpty()){
            selections.forEach((description) -> {
                int index = 0;
                for (int i = 0; i < part_descs.length; i++){
                    if (description.equals(part_descs[i])){
                        index = i;
                        break;
                    }
                }
                int part_no = part_nos[index];
                String sql = "" +
                "WITH upsert AS ( " +
                "UPDATE task_part SET amount=amount+1 " +
                "WHERE task_no=? AND part_no=? " +
                "RETURNING * " +
                ") " +
                "INSERT INTO task_part (task_no, part_no) " +
                "SELECT ?, ? " +
                "WHERE NOT EXISTS (SELECT * FROM upsert);";
                
                ArrayList<ValueObject> values = new ArrayList<>();
                
                ValueObject taskO = new ValueObject("int", task_no);
                ValueObject partO = new ValueObject("int", part_no);
                
                values.add(taskO);
                values.add(partO);
                values.add(taskO);
                values.add(partO);
                
                gui.databaseHandler.executeArrayInsert(sql, values);
            });
        }
        
        updateSelectedList();
    }//GEN-LAST:event_addButtonActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JList<String> partsList;
    private javax.swing.JButton removeButton;
    private javax.swing.JList<String> selectedList;
    private javax.swing.JTextField taskField;
    // End of variables declaration//GEN-END:variables

    private void updatePartsList() {
        part_nos = gui.databaseHandler.getIntArray("SELECT part_no FROM part ORDER BY part_no", "part_no");
        part_descs = gui.databaseHandler.getStringArray("SELECT part_name FROM part ORDER BY part_no", "part_name");

        partsList.setListData(part_descs);
    }

    private void updateSelectedList() {
        selected_part_nos = gui.databaseHandler.getIntArray("SELECT part_no FROM task_part WHERE task_no=" + task_no + "  ORDER BY part_no", "part_no");
        selected_part_names = gui.databaseHandler.getPartDetails(task_no);
        
        /*
        for (int i = 0; i < selected_part_nos.length; i++){
            if (selected_part_nos[i] != null){
                selected_part_names[i] = gui.databaseHandler.executeStringQuery("SELECT part_name FROM part WHERE part_no=?", 
                                                                                new ValueObject("int", selected_part_nos[i]), "part_name");
            } else {
                selected_part_names[i] = "NO PART NAME";
            }
        }*/
        
        for (int i : selected_part_nos){
            System.out.print(i + " ");
        }
        System.out.print("\n");
        //System.out.println(selected_part_nos.length + " == " + selected_part_names.length);

        selectedList.setListData(selected_part_names);
    }
}
